"""Initial migration: users, products, scraping_tasks

Revision ID: 598c0f276d2d
Revises: 
Create Date: 2026-07-11 17:39:42.150163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598c0f276d2d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='ID unik pengguna (UUID v4)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email pengguna, digunakan sebagai identifier login'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Password yang telah di-hash (bcrypt)'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Nama lengkap pengguna'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Status aktif akun'),
    sa.Column('shopee_shop_name', sa.String(length=255), nullable=True, comment='Nama toko di Shopee'),
    sa.Column('default_margin_percent', sa.Float(), nullable=False, comment='Margin keuntungan default dalam persen (contoh: 20.0 = 20%)'),
    sa.Column('shopee_admin_fee_percent', sa.Float(), nullable=False, comment='Persentase biaya admin Shopee (contoh: 2.0 = 2%)'),
    sa.Column('packaging_cost_rp', sa.Float(), nullable=False, comment='Biaya packaging dalam Rupiah per item'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Catatan tambahan dari pengguna'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False, comment='ID unik produk (UUID v4)'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='ID user pemilik produk ini'),
    sa.Column('source_url', sa.String(length=2048), nullable=False, comment='URL produk di Jakarta Notebook (sumber scraping)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status produk dalam pipeline: PENDING/SCRAPING/AI_PROCESSING/COMPLETED/FAILED'),
    sa.Column('raw_name', sa.String(length=500), nullable=True, comment='Nama produk asli dari halaman Jakarta Notebook'),
    sa.Column('raw_price', sa.Float(), nullable=True, comment='Harga asli produk dalam Rupiah'),
    sa.Column('raw_description', sa.Text(), nullable=True, comment='Deskripsi produk asli dari halaman Jakarta Notebook'),
    sa.Column('raw_image_url', sa.String(length=2048), nullable=True, comment='URL gambar produk asli dari Jakarta Notebook'),
    sa.Column('raw_stock', sa.Integer(), nullable=True, comment='Jumlah stok asli yang tersedia'),
    sa.Column('raw_sku', sa.String(length=255), nullable=True, comment='SKU / kode produk asli'),
    sa.Column('shopee_title', sa.String(length=120), nullable=True, comment='Judul produk SEO-optimized untuk Shopee (maks 120 karakter)'),
    sa.Column('shopee_description', sa.Text(), nullable=True, comment='Deskripsi produk marketing-oriented hasil AI untuk listing Shopee'),
    sa.Column('selling_price', sa.Float(), nullable=True, comment='Harga jual final (raw_price + margin + fee + packaging)'),
    sa.Column('enhanced_image_url', sa.String(length=2048), nullable=True, comment='URL gambar produk yang sudah diproses/enhanced di Supabase Storage'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('scraping_tasks',
    sa.Column('id', sa.UUID(), nullable=False, comment='ID unik task (UUID v4)'),
    sa.Column('owner_id', sa.UUID(), nullable=False, comment='ID user yang memiliki/memicu task ini'),
    sa.Column('product_id', sa.UUID(), nullable=True, comment='ID produk yang diproses oleh task ini (nullable jika task gagal sebelum produk dibuat)'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='ID task Celery yang dihasilkan saat task dikirim ke worker'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Status task: QUEUED/RUNNING/SUCCESS/FAILED/RETRYING'),
    sa.Column('current_step', sa.String(length=255), nullable=True, comment='Deskripsi langkah yang sedang dijalankan (untuk progress UI)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Jumlah percobaan ulang yang sudah dilakukan'),
    sa.Column('source_url', sa.String(length=2048), nullable=False, comment='URL produk yang diproses oleh task ini'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Pesan error jika task gagal'),
    sa.Column('error_traceback', sa.Text(), nullable=True, comment='Full traceback Python untuk debugging (hanya tersedia di FAILED)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraping_tasks_celery_task_id'), 'scraping_tasks', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_scraping_tasks_owner_id'), 'scraping_tasks', ['owner_id'], unique=False)
    op.create_index(op.f('ix_scraping_tasks_product_id'), 'scraping_tasks', ['product_id'], unique=False)
    op.create_index(op.f('ix_scraping_tasks_status'), 'scraping_tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scraping_tasks_status'), table_name='scraping_tasks')
    op.drop_index(op.f('ix_scraping_tasks_product_id'), table_name='scraping_tasks')
    op.drop_index(op.f('ix_scraping_tasks_owner_id'), table_name='scraping_tasks')
    op.drop_index(op.f('ix_scraping_tasks_celery_task_id'), table_name='scraping_tasks')
    op.drop_table('scraping_tasks')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
